# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cards_card_permision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_permision',
            field=models.CharField(choices=[('pu', 'public'), ('pr', 'private')], default='', max_length=1),
        ),
    ]
