# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20160618_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_permision',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='', max_length=10),
        ),
    ]
