# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20160618_1435'),
        ('cards', '0008_cards_private'),
    ]

    operations = [
    ]
