# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='card_permision',
        ),
        migrations.AddField(
            model_name='cards',
            name='Like',
            field=models.BooleanField(default=False),
        ),
    ]
