# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0013_auto_20160619_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={},
        ),
        migrations.RemoveField(
            model_name='cards',
            name='Like',
        ),
        migrations.AddField(
            model_name='like',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Cards'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
