# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0014_auto_20160619_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='cards',
            name='likes',
            field=models.ManyToManyField(default='', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
